services: 
  nginx: 
    container_name: nginx
    image: nginx:1.27.5-alpine 
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/var/www/html
    ports:
      - 80:80
    networks:
      - backend
    depends_on:
      - php

  php:
    container_name: php
    build: ./php
    volumes: 
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./src:/var/www/html
    expose:
      - 9000
    networks:
      - backend


networks:
  backend:
   driver: bridge