FROM php:8.3.20-fpm-alpine3.20

WORKDIR /var/www/html

RUN apk add --no-cache --update \
    libzip-dev \
    zip \
    unzip \
    oniguruma-dev \
    autoconf \
    gcc \
    g++ \
    make \
    bash \
    icu-dev \
    zlib-dev \
    mysql-client \
    libxml2-dev \
    && docker-php-ext-install pdo pdo_mysql mysqli

COPY --from=composer /usr/bin/composer /usr/bin/composer

